version: '3'

services:
  # Prometheus
  prometheus:
    image: prom/prometheus:${{ env.PROMETHEUS_TAG }}  # Sử dụng biến môi trường từ GitHub Actions
    build:
      context: .
      dockerfile: DockerfilePrometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules:/etc/prometheus/rules
    networks:
      - monitoring

  # SNMP Exporter
  snmp-exporter:
    image: prom/snmp-exporter:${{ env.SNMP_EXPORTER_TAG }}  # Sử dụng biến môi trường từ GitHub Actions
    build:
      context: .
      dockerfile: DockerfileSNMP-Exporter
    user: root
    ports:
      - "9116:9116"
    volumes:
      - ./snmp-exporter/snmp.yml:/etc/snmp-exporter/snmp.yml
    networks:
      - monitoring

  # Alert Manager
  alert-manager:
    image: prom/alertmanager:${{ env.ALERT_MANAGER_TAG }}  # Sử dụng biến môi trường từ GitHub Actions
    build:
      context: .
      dockerfile: DockerfileAlertManager
    user: root
    ports:
      - "9093:9093"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./alertmanager:/etc/alertmanager
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:${{ env.GRAFANA_TAG }}  # Sử dụng biến môi trường từ GitHub Actions
    build:
      context: .
      dockerfile: DockerfileGrafana
    user: root
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - .grafana.secret
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
