name: Deploy to Production (Main)

on:
  pull_request:
    branches:
      - main
    types:
      - merged

env:
  PROMETHEUS_TAG: "latest"           # Tag Docker cho Prometheus
  SNMP_EXPORTER_TAG: "latest"        # Tag Docker cho SNMP Exporter
  ALERT_MANAGER_TAG: "latest"        # Tag Docker cho Alert Manager
  GRAFANA_TAG: "latest"              # Tag Docker cho Grafana
  ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
  ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
  GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
  GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}

permissions:
  contents: read

jobs:
  # Job monitor
  monitor:
    name: Monitor
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set Grafana secrets in .grafana.secret
      - name: Set Grafana secrets in .grafana.secret
        run: |
          cd Monitoring
          echo "GF_SECURITY_ADMIN_USER=${{ secrets.GF_SECURITY_ADMIN_USER }}" > .grafana.secret
          echo "GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}" >> .grafana.secret

      # Install Monitoring Server
      - name: Install Monitoring Server
        run: |
          cd Monitoring
          sudo docker compose up -d
          sudo docker compose start
          cd snmp-exporter
          sudo docker run --rm -v $(pwd)/mibs:/opt/mibs -v $(pwd)/generator.yml:/opt/generator.yml -v $(pwd):/opt prom/snmp-generator:main generate
          cd ..
          sudo docker compose restart

  # Job Deploy
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: monitor
    steps:
      # Checkout code from repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          cd Network
          ansible-playbook -i inventory playbook.yml
