name: Deploy to Production (Main)

on:
  push:
    branches:
      - main

env:
  PROMETHEUS_TAG: "latest"           # Tag cho Prometheus trong nh치nh main
  SNMP_EXPORTER_TAG: "latest"        # Tag cho SNMP Exporter trong nh치nh main
  ALERT_MANAGER_TAG: "latest"        # Tag cho Alert Manager trong nh치nh main
  GRAFANA_TAG: "latest"              # Tag cho Grafana trong nh치nh main

jobs:
  build_monitor:
    name: Build Monitor
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set Docker tags based on branch (main)
      - name: Set up Docker tags for Main
        run: |
          echo "PROMETHEUS_TAG=latest" >> $GITHUB_ENV
          echo "SNMP_EXPORTER_TAG=latest" >> $GITHUB_ENV
          echo "ALERT_MANAGER_TAG=latest" >> $GITHUB_ENV
          echo "GRAFANA_TAG=latest" >> $GITHUB_ENV

      # Install Docker
      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt install docker-ce -y
          sudo usermod -aG docker ${USER}

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt update
          wget https://github.com/aquasecurity/trivy/releases/download/v0.57.1/trivy_0.57.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.57.1_Linux-64bit.deb

      # Build Docker images
      - name: Build Docker Images
        run: |
          cd Monitoring
          sudo docker-compose build

      # Run Docker Compose up
      - name: Run Docker Compose
        run: |
          cd Monitoring
          sudo docker-compose up -d
          
      # Install Monitoring Server
      - name: Install Monitoring Server
        run: |
          cd Monitoring
          sudo docker-compose start

  # Job to deploy with Ansible
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_monitor
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        run: |
          cd Network
          ansible-playbook -i inventory playbook.yml
